

GET http://localhost:3000/expenses
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkODcyNzFmOC0zMjk0LTQwMTItYmVjMy1mNTc2MmY2NTQ5ZmIiLCJlbWFpbCI6InJhbW9uLmNhY2hhbGVzQGV4YW1wbGUuY29tIiwibmFtZSI6IlJhbW9uIENhY2hhbGVzIiwidXNlckltYWdlIjpudWxsLCJ0aW1lU3RhbXAiOjE3NDQwNDg0NzQxNDUsImlhdCI6MTc0NDA0ODQ3NCwiZXhwIjoxNzQ0MDQ5Mzc0fQ.fieOO0Xuc5ti1jDTt6ZCwmF0f3MUizQ3Il1YW-1cReQ

GET http://localhost:3000/expenses/550e8400-e29b-41d4-a716-446655440001

POST http://localhost:3000/expenses
Content-Type: application/json

{
    "name": "Airplane ticket to Madrid",
    "amount": 70.0,
    "date": "2025-04-01T12:00:00Z",
    "paymentMethod": "Debit Card",
    "category": "Travel"
}

PATCH http://localhost:3000/expenses/550e8400-e29b-41d4-a716-446655440001
Content-Type: application/json

{
    "name": "Puma store clothing",
    "amount": 1000,
    "date": "2025-04-01T12:00:00Z",
    "paymentMethod": "Paypal",
    "category": "Technology and Communications"
}


DELETE http://localhost:3000/localhost:3000/expenses/550e8400-e29b-41d4-a716-446655440001